'use client';

import { FormEvent, useEffect, useRef, useState } from 'react';
import AdminFase78Nav from '@/components/admin/AdminFase78Nav';
import type { ProductoAdmin } from '@/lib/appsScriptPedidos';
import { pesos, resolverIntentoIdempotente, solicitarAdmin, type IntentoIdempotente } from '@/lib/fase8/clienteAdmin';
import { useSesionAdmin } from '@/lib/fase9/useSesionAdmin';

type Edicion = { nombre: string; categoria: string; unidad_medida: string; permite_decimal: string; paso_venta: number; precio_costo: number | ''; precio_venta: number; stock_minimo: number; prioridad: string; activo: string; imagen_url: string };

function editar(producto: ProductoAdmin): Edicion {
  return { nombre: producto.nombre, categoria: producto.categoria, unidad_medida: producto.unidad_medida, permite_decimal: producto.permite_decimal, paso_venta: Number(producto.paso_venta), precio_costo: producto.precio_costo === '' ? '' : Number(producto.precio_costo), precio_venta: Number(producto.precio_venta), stock_minimo: Number(producto.stock_minimo), prioridad: producto.prioridad, activo: producto.activo, imagen_url: producto.imagen_url };
}

export default function ProductosPage() {
  const { sesion, tiene } = useSesionAdmin();
  const puedeGestionar = tiene('productos:gestionar');
  const puedeAjustar = tiene('stock:ajustar');
  const [productos, setProductos] = useState<ProductoAdmin[]>([]); const [seleccion, setSeleccion] = useState('');
  const [cambio, setCambio] = useState<Edicion | null>(null); const [estado, setEstado] = useState('Cargando catálogo TEST...');
  const [delta, setDelta] = useState(0); const [motivo, setMotivo] = useState('recuento_fisico'); const [detalle, setDetalle] = useState('');
  const [nuevoId, setNuevoId] = useState('PROD-TEST-'); const [nuevoNombre, setNuevoNombre] = useState('');
  const intentoEditar = useRef<IntentoIdempotente | null>(null);
  const intentoAjustar = useRef<IntentoIdempotente | null>(null);
  const intentoCrear = useRef<IntentoIdempotente | null>(null);
  async function cargar() { try { const lista = await solicitarAdmin<ProductoAdmin[]>('/api/admin/productos'); setProductos(lista); setEstado(''); } catch (error) { setEstado(error instanceof Error ? error.message : 'No se pudo cargar el catálogo.'); } }
  useEffect(() => { void cargar(); }, []);
  function seleccionar(id: string) { setSeleccion(id); const p = productos.find((item) => item.id_producto === id); setCambio(p ? editar(p) : null); }
  async function guardar(evento: FormEvent) { evento.preventDefault(); if (!cambio) return; try { const payload = { producto_id: seleccion, cambios: cambio }; intentoEditar.current = resolverIntentoIdempotente(intentoEditar.current, 'PRODUCTO', payload); await solicitarAdmin('/api/admin/productos', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, idempotency_key: intentoEditar.current.clave }) }); intentoEditar.current = null; setEstado(`Producto ${seleccion} actualizado en TEST.`); await cargar(); } catch (error) { setEstado(error instanceof Error ? error.message : 'No se pudo actualizar.'); } }
  async function ajustar(evento: FormEvent) { evento.preventDefault(); try { const payload = { producto_id: seleccion, delta, motivo, observaciones: detalle }; intentoAjustar.current = resolverIntentoIdempotente(intentoAjustar.current, 'AJUSTE', payload); await solicitarAdmin('/api/admin/stock/ajustes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, idempotency_key: intentoAjustar.current.clave }) }); intentoAjustar.current = null; setEstado(`Stock de ${seleccion} ajustado con movimiento auditable.`); setDelta(0); await cargar(); } catch (error) { setEstado(error instanceof Error ? error.message : 'No se pudo ajustar stock.'); } }
  async function crear(evento: FormEvent) { evento.preventDefault(); try { const payload = { producto_id: nuevoId, producto: { nombre: nuevoNombre, categoria: 'Alimentos', unidad_medida: 'unidad', permite_decimal: 'NO', paso_venta: 1, precio_venta: 0, stock_minimo: 0, prioridad: 'media', activo: 'NO', imagen_url: '' } }; intentoCrear.current = resolverIntentoIdempotente(intentoCrear.current, 'NUEVO', payload); await solicitarAdmin('/api/admin/productos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, idempotency_key: intentoCrear.current.clave }) }); intentoCrear.current = null; setEstado(`Producto ${nuevoId} creado inactivo y con stock 0 en TEST.`); setNuevoId('PROD-TEST-'); setNuevoNombre(''); await cargar(); } catch (error) { setEstado(error instanceof Error ? error.message : 'No se pudo crear producto.'); } }
  const actual = productos.find((p) => p.id_producto === seleccion);
  return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-6xl"><AdminFase78Nav /><h1 className="font-serif text-3xl font-bold text-primary-dark">Productos y stock <span className="text-sm text-amber-700">TEST</span></h1><p className="mb-5 text-sm text-gray-600">El stock nunca se edita directamente: cada cambio exige un ajuste auditable.</p>{estado && <p role="status" className="mb-4 rounded bg-blue-50 p-3 text-sm">{estado}</p>}
    <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="max-h-[720px] overflow-y-auto rounded-xl bg-white p-3 shadow-sm"><label className="text-sm">Producto<select value={seleccion} onChange={(e) => seleccionar(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Seleccionar</option>{productos.map((p) => <option key={p.id_producto} value={p.id_producto}>{p.id_producto} · {p.nombre}</option>)}</select></label>{actual && <div className="mt-4 rounded bg-gray-50 p-3 text-sm"><p>Stock actual: <strong>{actual.stock_actual}</strong></p><p>Venta: <strong>{pesos(actual.precio_venta)}</strong></p><p>Estado: <strong>{actual.activo}</strong></p></div>}
      {puedeGestionar && <form onSubmit={crear} className="mt-5 space-y-2 border-t pt-4"><h2 className="text-sm font-semibold">Crear producto TEST</h2><input required value={nuevoId} onChange={(e) => setNuevoId(e.target.value)} className="w-full rounded border p-2 text-sm" aria-label="ID nuevo producto" /><input required value={nuevoNombre} onChange={(e) => setNuevoNombre(e.target.value)} className="w-full rounded border p-2 text-sm" placeholder="Nombre" /><button className="rounded border border-primary px-3 py-2 text-sm text-primary">Crear con stock 0</button></form>}
    </aside><div className="space-y-6">{cambio && puedeGestionar && <form onSubmit={guardar} className="grid gap-3 rounded-xl bg-white p-5 shadow-sm sm:grid-cols-2"><h2 className="sm:col-span-2 font-semibold">Editar {seleccion}</h2><Campo label="Nombre"><input value={cambio.nombre} onChange={(e) => setCambio({ ...cambio, nombre: e.target.value })} className="w-full rounded border p-2" /></Campo><Campo label="Categoría"><select value={cambio.categoria} onChange={(e) => setCambio({ ...cambio, categoria: e.target.value })} className="w-full rounded border p-2">{['Granel','Alimentos','Limpieza','Higiene'].map((x) => <option key={x}>{x}</option>)}</select></Campo><Campo label="Unidad"><select value={cambio.unidad_medida} onChange={(e) => setCambio({ ...cambio, unidad_medida: e.target.value })} className="w-full rounded border p-2">{['unidad','pack','kg'].map((x) => <option key={x}>{x}</option>)}</select></Campo><Campo label="Decimal"><select value={cambio.permite_decimal} onChange={(e) => setCambio({ ...cambio, permite_decimal: e.target.value })} className="w-full rounded border p-2"><option>SI</option><option>NO</option></select></Campo><Campo label="Paso"><input type="number" min="0.01" step="any" value={cambio.paso_venta} onChange={(e) => setCambio({ ...cambio, paso_venta: Number(e.target.value) })} className="w-full rounded border p-2" /></Campo><Campo label="Costo vigente"><input type="number" min="0" step="1" value={cambio.precio_costo} onChange={(e) => setCambio({ ...cambio, precio_costo: e.target.value === '' ? '' : Number(e.target.value) })} className="w-full rounded border p-2" /></Campo><Campo label="Precio venta"><input type="number" min="0" step="1" value={cambio.precio_venta} onChange={(e) => setCambio({ ...cambio, precio_venta: Number(e.target.value) })} className="w-full rounded border p-2" /></Campo><Campo label="Stock mínimo"><input type="number" min="0" step="any" value={cambio.stock_minimo} onChange={(e) => setCambio({ ...cambio, stock_minimo: Number(e.target.value) })} className="w-full rounded border p-2" /></Campo><Campo label="Prioridad"><select value={cambio.prioridad} onChange={(e) => setCambio({ ...cambio, prioridad: e.target.value })} className="w-full rounded border p-2">{['alta','media','baja'].map((x) => <option key={x}>{x}</option>)}</select></Campo><Campo label="Activo"><select value={cambio.activo} onChange={(e) => setCambio({ ...cambio, activo: e.target.value })} className="w-full rounded border p-2"><option>SI</option><option>NO</option></select></Campo><button className="sm:col-span-2 rounded bg-primary px-4 py-2 font-semibold text-white">Guardar producto TEST</button></form>}
      {cambio && puedeAjustar && <form onSubmit={ajustar} className="grid gap-3 rounded-xl border-2 border-amber-300 bg-amber-50 p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-semibold">Ajuste auditable de stock</h2><p className="sm:col-span-2 text-xs text-gray-600">Actor: {sesion?.nombre || sesion?.actor_id}</p><Campo label="Delta (+ entrada / - salida)"><input required type="number" step="any" value={delta} onChange={(e) => setDelta(Number(e.target.value))} className="w-full rounded border p-2" /></Campo><Campo label="Motivo"><select value={motivo} onChange={(e) => setMotivo(e.target.value)} className="w-full rounded border p-2">{['recuento_fisico','merma','error_carga_inicial','devolucion','otro'].map((x) => <option key={x}>{x}</option>)}</select></Campo><Campo label="Observaciones"><input required={motivo === 'otro'} value={detalle} onChange={(e) => setDetalle(e.target.value)} className="w-full rounded border p-2" /></Campo><button className="sm:col-span-2 rounded bg-amber-700 px-4 py-2 font-semibold text-white">Aplicar ajuste TEST</button></form>}
    </div></div>
  </div></main>;
}

function Campo({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm">{label}<span className="mt-1 block">{children}</span></label>; }
