import test from 'node:test';
import assert from 'node:assert/strict';
import { ID_TEST_B2,NOMBRE_TEST_B2,FAMILIAS_B2,planificarFamiliasB2,prepararFamiliasProductoB2Test } from '../scripts/lib/familias-b2.mjs';
import { COLUMNAS_FAMILIAS_PRODUCTO } from '../src/lib/familiasProducto.ts';
function estado(){return {meta:{spreadsheetId:ID_TEST_B2,properties:{title:NOMBRE_TEST_B2},sheets:[{properties:{title:'PRODUCTOS',sheetId:1,gridProperties:{columnCount:26}}},{properties:{title:'DETALLE_COMPRAS',sheetId:2,gridProperties:{columnCount:26}}}]},valores:{PRODUCTOS:[['id_producto','stock_actual'],['PROD-QA',4]],DETALLE_COMPRAS:[['producto_id'],['PROD-QA']]}};}
function adapter(){let s=estado(),aplicadas=0,backups=0;return {leer:async()=>structuredClone(s),timestamp:()=> 'fixture',backup:async()=>{backups++;return 'backup-qa';},verificarBackup:async()=>true,aplicar:async reqs=>{aplicadas++;for(const r of reqs){if(r.addSheet){const p=r.addSheet.properties;s.meta.sheets.push({properties:p});s.valores[p.title]=[];}if(r.updateCells){const nombre=s.meta.sheets.find(x=>x.properties.sheetId===r.updateCells.range.sheetId).properties.title;const hs=r.updateCells.rows[0].values.map(v=>v.userEnteredValue.stringValue);s.valores[nombre][0]??=[];s.valores[nombre][0].push(...hs);}}},contar:()=>({aplicadas,backups}),corromper:()=>{s.valores.PRODUCTOS[1][1]=99;}};}
test('B2: headers familiares exactos; plan solo escribe row 1 y crea hoja vacía',()=>{assert.deepEqual(FAMILIAS_B2,[...COLUMNAS_FAMILIAS_PRODUCTO]);for(const r of planificarFamiliasB2(estado().meta,estado().valores).requests)if(r.updateCells)assert.equal(r.updateCells.range.endRowIndex,1);});
test('B2: dos ejecuciones, un backup y segunda sin cambios; historia intacta',async()=>{const a=adapter();const r=await prepararFamiliasProductoB2Test(a);assert.equal(r.readback.valores.PRODUCTOS[1][1],4);assert.equal((await prepararFamiliasProductoB2Test(a)).cambios,0);assert.deepEqual(a.contar(),{aplicadas:1,backups:1});});
test('B2: backup inválido aborta antes de escritura',async()=>{const a=adapter();a.verificarBackup=async()=>false;await assert.rejects(prepararFamiliasProductoB2Test(a),/Backup/);assert.equal(a.contar().aplicadas,0);});
test('B2: concurrencia y readback corrupto detienen la migración',async()=>{const a=adapter();a.verificarBackup=async()=>{a.corromper();return true;};await assert.rejects(prepararFamiliasProductoB2Test(a),/concurrente/);const b=adapter(),aplicar=b.aplicar;b.aplicar=async r=>{await aplicar(r);b.corromper();};await assert.rejects(prepararFamiliasProductoB2Test(b),/histórica/);});
test('B2: destino incierto, headers/SKU duplicados y familia no vacía fallan cerrado',()=>{for(const mutar of [s=>s.meta.spreadsheetId='otro',s=>s.meta.properties.title='Producción',s=>s.valores.PRODUCTOS[0].push('id_producto'),s=>s.valores.PRODUCTOS.push(['PROD-QA',5]),s=>{s.meta.sheets.push({properties:{title:'FAMILIAS_PRODUCTO'}});s.valores.FAMILIAS_PRODUCTO=[FAMILIAS_B2,['FAM-REAL']];}]){const s=estado();mutar(s);assert.throws(()=>planificarFamiliasB2(s.meta,s.valores));}});
